feat: Add ipaddress and operatingsystem fields to virtualmachine
glpi-project/inventory_format pull request #146
Opened 2024-10-31 18:11 UTC by g-bougard

Add support to specify ip address and operating system on virtualmachine object.

Related ticket: #32800 #34616

2024-10-31 19:50 UTC, stonebuzz requested changes

2024-10-31 19:50 UTC, stonebuzz commented on inventory.schema.json
> +              },
```suggestion
              "ipaddress": {
                "type": "string",
                "format": "ipv4",
                "title": "Virtualmachine ip",
                "examples": [
                  "127.0.0.1"
                ],
              },
```
In addition :
do you know if it's possible to recover IPV6 or not?

2024-10-31 19:50 UTC, stonebuzz commented on inventory.schema.json
> +                "$ref": "#/properties/content/properties/operatingsystem"
@trasher  does referring to this `#/properties/content/properties/operatingsystem`

imply that all fields must be retrieved (`arch`, `bootime`, `fullname`, `name` etc.)?

```json
        "operatingsystem": {
          "type": "object",
          "properties": {
            "arch": {
              "type": "string",
              "examples": [
                "x86_64"
              ]
            },
            "boot_time": {
              "examples": [
                "2017-06-08 07:06:47"
              ],
              "$ref": "#/definitions/datetime"
            },
            "dns_domain": {
              "type": "string",
              "examples": [
                "ad.example.com"
              ]
            },
            "fqdn": {
              "type": "string",
              "examples": [
                "skynet.ad.example.com"
              ]
            },
            "full_name": {
              "type": "string",
              "examples": [
                "Fedora release 25 (Twenty Five)",
                "Debian GNU/Linux unstable (sid)",
                "Microsoft(R) Windows(R) Server 2003, Enterprise Edition x64"
              ]
            },
            "hostid": {
              "type": "string",
              "examples": [
                "007f0100"
              ]
            },
            "install_date": {
              "examples": [
                "2013-08-09 12:00:21"
              ],
              "$ref": "#/definitions/dateordatetime"
            },
            "kernel_name": {
              "type": "string",
              "examples": [
                "linux",
                "freebsd",
                "hpux",
                "win32"
              ]
            },
            "kernel_version": {
              "type": "string",
              "examples": [
                "4.11.3-200.fc25.x86_64",
                "5.2.10.4"
              ]
            },
            "name": {
              "type": "string",
              "title": "Operating system name ('Distributor ID' in LSB terms)",
              "examples": [
                "Fedora",
                "Debian",
                "Ubuntu",
                "CentOS",
                "SUSE LINUX",
                "Windows",
                "OS X",
                "FreeBSD",
                "AIX",
                "Android"
              ]
            },
            "ssh_key": {
              "type": "string",
              "examples": [
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgGz/LeCPvEeLKgqfDaG0EywPb0dgjSwW9JuAV2YMOcSX8PbyUuX+DxIth9OOjfQqFF/TRY1UshKMjVoQxKk1HzKiE9bk1FOgxmkhwjQWmRU64DcBqZqxkDNgqgz3YPzR7W46O3AuMOKsm/9lv4biwLd32ENPdezloiUrsS05OtzBbZWtlPCu0+t2MwhDAodF7rphf2Cj8ygNjavmFheFupRp3M7LxtyUhLPfp23t1ddT3U4iJtioW1PsWzxdkBD5wbrZ5THMjhhKP1/HjMUP8GSo1Jj0nDGu8m0qZq10pcVZxr5ZZ10QRqnpbgV1tYCTaVklzKFRZEiO2myGAWryD"
              ]
            },
            "service_pack": {
              "type": "string",
              "examples": [
                "Service Pack 1"
              ]
            },
            "timezone": {
              "type": "object",
              "required": [
                "name",
                "offset"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "examples": [
                    "CEST"
                  ]
                },
                "offset": {
                  "type": "string",
                  "examples": [
                    "+0200"
                  ],
                  "pattern": "^[+-][0-9]{4}$"
                }
              }
            },
            "version": {
              "type": "string",
              "title": "Operating system version ('Release' in LSB terms)",
              "examples": [
                "25",
                "5.4",
                "2003",
                "11.04"
              ]
            }
          },
          "additionalProperties": false
        },
 ```

2024-11-04 07:15 UTC, trasher commented on inventory.schema.json
> +              },
I think we should not limit the format to any version of IP. We already have several existing cases: with two fields, or with a `anyOf` condition (I guess this one is preferable).

2024-11-04 07:17 UTC, trasher commented on inventory.schema.json
> +                "$ref": "#/properties/content/properties/operatingsystem"
> imply that all fields must be retrieved (`arch`, `bootime`, `fullname`, `name` etc.)?

I'm not sure I understand :/ So far, all fields *may* be retrieved, since no one is required.

2024-11-04 08:01 UTC, stonebuzz commented on inventory.schema.json
> +                "$ref": "#/properties/content/properties/operatingsystem"
you're right, none of them are required, It may not be useful to make a reference to this declaration, as we won't be retrieving all the fields from the ESX

2024-11-04 08:27 UTC, trasher commented on inventory.schema.json
> +                "$ref": "#/properties/content/properties/operatingsystem"
The format just describes possible information for a given subset. Existing OS property already have all possible information; and therefore can just be reused from the format point of view (note it will also be from GLPI code point of view). The fact a specific system won't give all possible information is not a problem (and format should just not care about that).

2024-11-04 09:19 UTC, g-bougard commented on inventory.schema.json
> +                "$ref": "#/properties/content/properties/operatingsystem"
@stonebuzz 

To me the question is more to keep format consistent and avoid to duplicate definition with the risk to have confusing differences or mistakes.

Regarding ESX case, the only field I'm able to provide from the agent point of view are "full_name", "fqdn", "domain_name" and "boot_time". I think we could provide more fields for containers cases if we decide to add them.

Anyway, using same format here could guide GLPI development part to reuse code and limit maintenance.

2024-11-04 13:29 UTC, g-bougard commented on inventory.schema.json
> +              },
Made some tests with `anyOf` and it seems to work as expected.

2024-11-04 14:13 UTC, trasher approved these changes

2024-11-04 15:55 UTC, stonebuzz approved these changes

2024-11-04 17:12 UTC, merged