List instances under related database, makes updates easier
glpi-project/inventory_format pull request #45
Opened 2021-06-16 14:08 UTC by trasher

2021-06-16 14:09 UTC, g-bougard approved these changes

2021-06-17 09:45 UTC, g-bougard commented on lib/php/Converter.php
> +                //old proeperty
Little typo in comment

2021-06-17 09:51 UTC, g-bougard requested changes
"port" is still on "required" properties for "databases" but it has been moved to "instances" members

2021-06-17 10:00 UTC, g-bougard approved these changes

2021-06-18 05:47 UTC, g-bougard reviewed
I see you added a commit "More fixes" which adds a lot of changes in inventory schema. I don't understand what are these schema "fixes" without explanation. It seems even to me you may introduce back specs that was removed in the original XML format.

Finally, the PR title has less and less purpose with the PR content.

2021-06-18 06:15 UTC, trasher commented
This PR is still a draft

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +          "additionalProperties": false
I've added this on all `content` properties but `cartridges` that can contains several values.

With this, validation will fail if JSON contains a property not listed in the schema. From the inventories I have locally (20 or 30K inventory files); I had to drop some, and I can convert some others.

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +              "focallength": {
Typo

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +                  "ifalias": {
Existing, and used

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +              "ifalias": {
Existing, and used

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +              "ips": {
Existing and used

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +              "serial": {
Existing and used

2021-06-21 14:40 UTC, trasher commented on inventory.schema.json
> +              "instances": {
Use a subproperty fo instances, remove instance only data from database

2021-06-22 07:20 UTC, cedric-anne approved these changes

2021-06-22 08:22 UTC, g-bougard commented on inventory.schema.json
> +              "ips": {
Agree too

2021-06-22 08:22 UTC, g-bougard commented on inventory.schema.json
> +              "serial": {
Agree too

2021-06-22 08:22 UTC, g-bougard commented on inventory.schema.json
> +              "instances": {
"is_active" & "is_onbackup" properties are also still set on "databases" object. So why keeping them on "databases" object ?
Also about "creation_date" & "update_date", why are they kept on databases object ? I think they would make more sense on "instances" objects.

2021-06-23 07:41 UTC, orthagh approved these changes

2021-06-23 08:36 UTC, trasher commented on inventory.schema.json
> +                  "ifalias": {
Indeed, this is not existing in connections; I've removed it.

2021-06-28 07:05 UTC, merged