Keep only databases instances, add schemas list
glpi-project/inventory_format pull request #46
Opened 2021-06-29 11:58 UTC by trasher

Proposal following morning meeting

2021-06-29 12:00 UTC, trasher commented on examples/computer_2_partial_dbs.json
> +        "databases": [
May also be "databases_instances" or "databases_services".

2021-06-29 12:07 UTC, orthagh approved these changes

2021-06-29 12:20 UTC, orthagh commented on examples/computer_2_partial_dbs.json
> +        "databases": [
for this part, i may prefer to be precise, so "databases_instances".

"Schema" below is good

2021-06-29 13:38 UTC, g-bougard requested changes

2021-06-29 13:38 UTC, g-bougard commented on inventory.schema.json
> +              "port"
I don't think **port** must be **required**.

2021-06-29 13:38 UTC, g-bougard commented on inventory.schema.json
> +              "schemas": {
Here I would prefer **databases** or maybe **namespaces**. I think **schemas** can be confusing with the **database schema** term which is in my mind how to initialize a database.

2021-06-29 13:38 UTC, g-bougard commented on inventory.schema.json
>              "properties": {
I think **size** should be added in the properties list of "databases_instances" as it may not be equal to the sum of "databases" sizes and it can be found in some cases.

2021-06-29 13:38 UTC, g-bougard commented on inventory.schema.json
> -                    },
I think at least **is_active** & maybe **is_onbackup** could eventually be also kept at the **databases** level.

2021-06-29 13:38 UTC, g-bougard commented on inventory.schema.json
> -                      ],
If we keep **is_onbackup**, **last_backup_date** should probably also be kept.

2021-06-29 13:38 UTC, g-bougard commented on inventory.schema.json
>              "properties": {
Also **path** property could be meaningful in some cases.

2021-06-29 14:29 UTC, trasher commented on inventory.schema.json
>              "properties": {
I do not know if e can have a size per instance, but it can be added.
As for the path, what is the purpose? For sockets for example? In that case, either port or path should be required, but I do not know if this is possible in json schema

2021-06-29 14:29 UTC, trasher commented on inventory.schema.json
> +              "schemas": {
ping @orthagh

2021-06-29 14:31 UTC, trasher commented on inventory.schema.json
> -                    },
I have no idea, keeping them on both sides is ok for me.

2021-06-29 14:34 UTC, trasher commented on inventory.schema.json
> +              "schemas": {
:-1: for `databases` anyway

2021-06-29 14:42 UTC, g-bougard commented on inventory.schema.json
>              "properties": {
**path** in my mind would better be the storage path. For example, it could be `/var/lib/mysql` but I think it can have more sense for few other database types. Anyway we can just keep this possibility for a future format update.
And about **port** requirement, I guess some databases instances won't have a port.

2021-06-29 14:56 UTC, g-bougard commented on inventory.schema.json
> +                "type": "integer"
integer ? sure ? O:)

2021-06-29 14:57 UTC, g-bougard commented on inventory.schema.json
>                        "type": "integer"
Here too: you should probably also need to tell in a comment the expected unit.

2021-06-29 15:18 UTC, trasher commented on inventory.schema.json
>              "properties": {
ok, changes has been done already

2021-06-29 15:18 UTC, trasher commented on inventory.schema.json
> +                "type": "integer"
erf :D good catch

2021-06-29 15:20 UTC, trasher commented on inventory.schema.json
> +                "type": "integer"
Indeed, yes. It seems like we rely on "MB" most of the time.

2021-06-30 05:15 UTC, trasher commented on inventory.schema.json
> +              "schemas": {
> -1 for `databases` anyway

Thinking about that; since this is already under a `databases_instances` node, it may be not so confusing; and I've nothing better to propose :p

2021-06-30 06:48 UTC, orthagh commented on inventory.schema.json
> +              "schemas": {
i agree finaly, it's ok for databases, as a child node, it should be ok

2021-06-30 07:50 UTC, cedric-anne commented on examples/computer_2_partial_dbs.json
> +        "databases_instances": [
IMHO `databases_services` may be more appropriate, and less subject to ambiguity.

I search for `database instance`, to see if it is a common term, and the first article I found (https://www.lifewire.com/database-instance-1019612) says:
> The term "database instance" is frequently misunderstood because it means different things to different vendors. The most common use is in connection with Oracle database implementations.

2021-06-30 08:03 UTC, trasher commented on examples/computer_2_partial_dbs.json
> +        "databases_instances": [
I'mOK with `services`.

2021-06-30 09:36 UTC, g-bougard commented on examples/computer_2_partial_dbs.json
> +        "databases_instances": [
This makes sens to me too.

2021-06-30 11:27 UTC, trasher commented on examples/computer_2_partial_dbs.json
> +        "databases_instances": [
Done

2021-06-30 11:28 UTC, trasher commented on inventory.schema.json
> +              "schemas": {
Done

2021-06-30 11:54 UTC, cedric-anne approved these changes

2021-06-30 12:36 UTC, g-bougard approved these changes

2021-06-30 17:09 UTC, merged