Fixes
glpi-project/inventory_format pull request #72
Opened 2022-06-06 10:01 UTC by trasher

2022-06-06 10:02 UTC, orthagh approved these changes

2022-06-06 12:34 UTC, g-bougard requested changes
Checking glpi-project/glpi#11811 I can see the proposed XML CONTROLLERS nodes also include a "SERIAL" which is also not supported  in inventory.
You should probably add this support at the same time.

2022-06-06 12:52 UTC, g-bougard approved these changes

2022-06-07 06:27 UTC, orthagh approved these changes

2022-06-07 12:03 UTC, cedric-anne approved these changes

2022-06-08 07:05 UTC, g-bougard approved these changes

2022-06-08 07:38 UTC, merged